<?php
/**
 *
 * @copyright Copyright (c) 2020 cleverstone
 *
 */

namespace app\components;

use Yii;
use yii\base\Component;
use yii\web\UploadedFile;
use yii\base\DynamicModel;
use http\Exception\UnexpectedValueException;

/**
 * 上传文件组件
 *
 * ```php
 * //配置
 * components = [
 * // 文件上传组件
 *  'uploads' => [
 *      'class' => 'app\components\Uploads',
 *      'type' => \app\components\Uploads::LOCAL_UPLOAD_ENGINE_SYMBOL,
 *      'configs' => [
 *      'rootUrl' => '@web/upload', // 外链域名
 *      'rootPath' => '@webroot' . DIRECTORY_SEPARATOR . 'upload', // 上传地址
 *      // 其他配置，后期接云存储自行配置
 *      ],
 *      // 其他配置项参见当前类的公共属性定义。
 *  ],
 * ]
 * ```
 *
 * ```php
 *  // 调用
 *  \YII::$app->uploads->execute($name)
 * ```
 *
 * @author cleverstone
 * @since 1.0
 */
class Uploads extends Component
{
    /* 上传场景：图片、文件、音频、视频 */
    const SCENARIO_IMAGE = 'image';
    const SCENARIO_FILE = 'file';
    const SCENARIO_AUDIO = 'audio';
    const SCENARIO_VIDEO = 'video';

    /* 图片存储空间名 */
    const IMAGE_STORAGE_BUCKET = 'image';
    /* 文件存储空间名 */
    const FILE_STORAGE_BUCKET = 'file';
    /* 音频存储空间名 */
    const AUDIO_STORAGE_BUCKET = 'audio';
    /* 视频存储空间名 */
    const VIDEO_STORAGE_BUCKET = 'video';

    /* 上传引擎标识 */
    const LOCAL_UPLOAD_ENGINE_SYMBOL = 'LOCAL';
    const QINIU_UPLOAD_ENGINE_SYMBOL = 'QINIU';

    // 图片验证规则
    private $_imageRules = [];
    // 文件验证规则
    private $_fileRules = [];
    // 音频验证规则
    private $_audioRules = [];
    // 视频验证规则
    private $_videoRules = [];

    // 图片支持的扩展名
    public $imageSupportExt = ['png', 'jpg', 'jpeg', 'gif',];
    // 文件支持的扩展名
    public $fileSupportExt = ['zip', 'RAR', 'txt', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'pdf',];
    // 音频支持的扩展名
    public $audioSupportExt = ['cda', 'wav', 'mp3', 'aiff', 'aif', 'mid', 'wma', 'ra', 'vqf', 'ape',];
    // 视频支持的扩展名
    public $videoSupportExt = ['avi', 'mov', 'rmvb', 'rm', 'flv', 'mp4', '3gp',];

    // 图片大小最大值
    public $imageMaxSize = 1024 * 1024 * 10;
    // 文件大小最大值
    public $fileMaxSize = 1024 * 1024 * 250;
    // 音频大小最大值
    public $audioMaxSize = 1024 * 1024 * 150;
    // 视频大小最大值
    public $videoMaxSize = 1024 * 1024 * 500;

    // 同时上传最大数量
    public $attachMaxFiles = 10;

    /**
     * 上传引擎
     * - self::LOCAL_UPLOAD_ENGINE_SYMBOL 本地
     * - self::QINIU_UPLOAD_ENGINE_SYMBOL 七牛云
     * @var string
     */
    public $type = self::LOCAL_UPLOAD_ENGINE_SYMBOL;

    /**
     * 配置项
     * @var array
     * 当`type`是`self::LOCAL_UPLOAD_ENGINE_SYMBOL`
     * - `rootUrl` string 文件的根域名
     * - `rootPath` string 文件的根路径
     *
     * 当`type`是`self::QINIU_UPLOAD_ENGINE_SYMBOL`
     *
     */
    public $configs;

    /**
     * 初始化组件
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (empty($this->_imageRules)) {
            $this->setImageRules();
        }

        if (empty($this->_fileRules)) {
            $this->setFileRules();
        }

        if (empty($this->_audioRules)) {
            $this->setAudioRules();
        }

        if (empty($this->_videoRules)) {
            $this->setVideoRules();
        }

        // 如果`type`是函数，则执行
        if (is_function($this->type)) {
            $this->type = call_user_func($this->type);
        }
    }

    /**
     * 上传附件
     * @param string $name 附件字段名，如：photo
     * @param string $saveDirectory 保存目录，如：order
     * @param string $pathPrefix 路径前缀，如：100.1.0
     * @param string $scenario 上传附件类型场景，如：self::SCENARIO_IMAGE
     * @return string|true
     * @throws \yii\base\Exception
     */
    public function execute($name, $saveDirectory = 'common', $pathPrefix = '', $scenario = self::SCENARIO_IMAGE)
    {
        switch ($this->type) {
            case self::LOCAL_UPLOAD_ENGINE_SYMBOL: // 本地
                return $this->uploadAttachmentLocal($name, $saveDirectory, $pathPrefix, $scenario);
            case self::QINIU_UPLOAD_ENGINE_SYMBOL: // 七牛
                return $this->uploadAttachmentQiniu($name, $saveDirectory, $pathPrefix, $scenario);
            default:
                throw new UnexpectedValueException(t('the upload engine is not defined'));
        }
    }

    /**
     * 上传附件(七牛云)
     * @param $name
     * @param $saveDirectory
     * @param $pathPrefix
     * @param $scenario
     * @return true|string
     */
    protected function uploadAttachmentQiniu($name, $saveDirectory, $pathPrefix, $scenario)
    {
        return true;
    }

    /**
     * 上传附件(本地)
     * @param string $name 附件字段名，如：photo
     * @param string $saveDirectory 保存目录，如：order
     * @param string $pathPrefix 路径前缀，如：100.1.0
     * @param string $scenario 上传附件类型场景，如：self::SCENARIO_IMAGE
     * @return true|string
     * @throws \yii\base\Exception
     */
    protected function uploadAttachmentLocal($name, $saveDirectory = 'common', $pathPrefix = '', $scenario = self::SCENARIO_IMAGE)
    {
        // 文件保存路径
        $savePath = $this->generateAttachmentSavePath($scenario, $saveDirectory, $pathPrefix);
        // 上传文件实例集合
        $uploadedFileInstanceMap = UploadedFile::getInstancesByName($name);
        // 上传前校验
        $validateResult = $this->validateFiles($scenario, $uploadedFileInstanceMap);
        if ($validateResult !== true) {
            return $validateResult;
        }

        /* @param UploadedFile $uploadedFileInstance */
        foreach ($uploadedFileInstanceMap as $uploadedFileInstance) {
            $filename = $this->generateFilename();
            $ext = $uploadedFileInstance->extension;
            $uploadedFileInstance->saveAs($savePath . DIRECTORY_SEPARATOR . $filename . '.' . $ext);
        }

        return true;
    }

    /**
     * 上传校验
     * @param string $scenario 场景
     * @param UploadedFile[] $files
     * @return true|string
     * @throws \yii\base\InvalidConfigException
     */
    protected function validateFiles($scenario, $files)
    {
        /* @param UploadedFile $uploadedFileInstance */
        switch ($scenario) {
            case self::SCENARIO_FILE:
                $rule = $this->getFileRules();
                break;
            case self::SCENARIO_AUDIO:
                $rule = $this->getAudioRules();
                break;
            case self::SCENARIO_VIDEO:
                $rule = $this->getVideoRules();
                break;
            case self::SCENARIO_IMAGE:
            default:
                $rule = $this->getImageRules();
        }

        $model = DynamicModel::validateData(compact('files'), $rule);
        if ($model->hasErrors()) {
            return current($model->firstErrors) ?: '';
        }

        return true;
    }

    /**
     * 获取图片验证规则
     * @return array
     */
    public function getImageRules()
    {
        return $this->_imageRules;
    }

    /**
     * 获取文件验证规则
     * @return array
     */
    public function getFileRules()
    {
        return $this->_fileRules;
    }

    /**
     * 获取音频验证规则
     * @return array
     */
    public function getAudioRules()
    {
        return $this->_audioRules;
    }

    /**
     * 获取视频验证规则
     * @return array
     */
    public function getVideoRules()
    {
        return $this->_videoRules;
    }

    /**
     * 设置图片验证规则
     * @param array $rules 验证规则
     * @return $this
     */
    public function setImageRules($rules = [])
    {
        if (!empty($rules)) {
            $this->_imageRules = $rules;
        }

        $this->_imageRules = [
            [
                'files',
                'image',
                'skipOnEmpty' => false,
                'extensions' => implode(',', $this->imageSupportExt),
                // 最大10M
                'maxSize' => $this->imageMaxSize,
                'maxFiles' => $this->attachMaxFiles,
            ],
        ];

        return $this;
    }

    /**
     * 设置文件验证规则
     * @param array $rules 验证规则
     * @return $this
     */
    public function setFileRules($rules = [])
    {
        if (!empty($rules)) {
            $this->_fileRules = $rules;
        }

        $this->_fileRules = [
            [
                'files',
                'file',
                'skipOnEmpty' => false,
                'extensions' => implode(',', $this->fileSupportExt),
                // 最大10M
                'maxSize' => $this->fileMaxSize,
                'maxFiles' => $this->attachMaxFiles,
            ],
        ];

        return $this;
    }

    /**
     * 设置音频验证规则
     * @param array $rules 验证规则
     * @return $this
     */
    public function setAudioRules($rules = [])
    {
        if (!empty($rules)) {
            $this->_audioRules = $rules;
        }

        $this->_audioRules = [
            [
                'files',
                'file',
                'skipOnEmpty' => false,
                'extensions' => implode(',', $this->audioSupportExt),
                // 最大10M
                'maxSize' => $this->audioMaxSize,
                'maxFiles' => $this->attachMaxFiles,
            ],
        ];

        return $this;
    }

    /**
     * 设置视频验证规则
     * @param array $rules 验证规则
     * @return $this
     */
    public function setVideoRules($rules = [])
    {
        if (!empty($rules)) {
            $this->_videoRules = $rules;
        }

        $this->_videoRules = [
            [
                'files',
                'file',
                'skipOnEmpty' => false,
                'extensions' => implode(',', $this->videoSupportExt),
                // 最大10M
                'maxSize' => $this->videoMaxSize,
                'maxFiles' => $this->attachMaxFiles,
            ],
        ];

        return $this;
    }

    /**
     * 附件外链
     * @param string $fileBasename 文件路径 如：order/2022/1548754.png
     * @param string $scenario 附件类型上传场景
     * @return string
     */
    public function getAttachmentUrl($fileBasename, $scenario = self::SCENARIO_IMAGE)
    {
        $bucket = $this->getBucketByScenario($scenario);
        $attachmentUrl = rtrim(Yii::getAlias($this->configs['rootUrl']), '/') . '/' . str_replace('\\', '/', $bucket . '/' . ltrim($fileBasename, '\\/'));
        if (strncasecmp($attachmentUrl, 'http', 4)) {
            return rtrim(Yii::$app->request->getHostInfo(), '/') . '/' . ltrim($attachmentUrl, '/');
        }

        return $attachmentUrl;
    }

    /**
     * 删除附件
     * @param string $filepath 文件路径
     * @return bool
     */
    public function unlinkFile($filepath)
    {
        switch ($this->type) {
            case self::LOCAL_UPLOAD_ENGINE_SYMBOL:
                return @unlink($filepath);
            case self::QINIU_UPLOAD_ENGINE_SYMBOL:
                return true;
            default:
                throw new UnexpectedValueException(t('the upload engine is not defined'));
        }
    }

    /**
     * 生成文件名
     * @return string
     * @throws \yii\base\Exception
     */
    protected function generateFilename()
    {
        return date('YmdHis') . random_string(true, 10);
    }

    /**
     * 根据场景获取上传空间名
     * @param string $scenario 上传文件类型场景
     * @return string
     */
    protected function getBucketByScenario($scenario)
    {
        switch ($scenario) {
            case self::SCENARIO_IMAGE:
                $bucket = self::IMAGE_STORAGE_BUCKET;
                break;
            case self::SCENARIO_FILE:
                $bucket = self::FILE_STORAGE_BUCKET;
                break;
            case self::SCENARIO_AUDIO:
                $bucket = self::AUDIO_STORAGE_BUCKET;
                break;
            case self::SCENARIO_VIDEO:
                $bucket = self::VIDEO_STORAGE_BUCKET;
                break;
            default:
                throw new \InvalidArgumentException(t('the file upload scenario is incorrect'));
        }

        return $bucket;
    }

    /**
     * 获取文件路径前缀
     * @param string $pathPrefix 文件路径前缀（待处理）
     * @param string $separator 路径分隔符
     * @return array|string|string[]|null
     */
    protected function getPathPrefix($pathPrefix, $separator = DIRECTORY_SEPARATOR)
    {
        $_pathPrefix = '';
        if (!empty($pathPrefix)) {
            $_pathPrefix = preg_replace('%[.\-]%', $separator, trim($pathPrefix, '.-'));
        }

        return $_pathPrefix;
    }

    /**
     * 获取附件完整的保存路径
     * @param string $scenario 场景
     * @param string $saveDirectory 保存目录，如：order
     * @param string $pathPrefix 路径前缀（如：100.10.1）
     * @return false|string
     */
    protected function generateAttachmentSavePath($scenario, $saveDirectory, $pathPrefix)
    {
        $bucket = $this->getBucketByScenario($scenario);
        $_pathPrefix = $this->getPathPrefix($pathPrefix);

        $savePath = '';
        // 拼接上传地址
        $savePath .= rtrim($this->configs['rootPath'], '\\/') . DIRECTORY_SEPARATOR;
        // 拼接上传空间
        $savePath .= $bucket . DIRECTORY_SEPARATOR;
        // 拼接保存目录
        $savePath .= $saveDirectory . DIRECTORY_SEPARATOR;
        if (!empty($_pathPrefix)) {
            // 拼接路径前缀
            $savePath .= $_pathPrefix;
        }

        return Yii::getAlias($savePath);
    }
}